"""Shared constants for the news text classification module."""

from __future__ import annotations


CATEGORY_LABELS: list[str] = [
    "财经",
    "体育",
    "科技",
    "娱乐",
    "社会",
    "教育",
    "军事",
    "汽车",
]

CATEGORY_ALIASES: dict[str, str] = {
    "财产": "财经",
    "金融": "财经",
    "finance": "财经",
    "financial": "财经",
    "business": "财经",
    "economy": "财经",
    "股票": "财经",
    "证券": "财经",
    "经济": "财经",
    "彩票": "财经",
    "球类": "体育",
    "足球": "体育",
    "篮球": "体育",
    "运动": "体育",
    "sport": "体育",
    "sports": "体育",
    "it": "科技",
    "IT": "科技",
    "互联网": "科技",
    "数码": "科技",
    "科学": "科技",
    "tech": "科技",
    "technology": "科技",
    "science": "科技",
    "digital": "科技",
    "明星": "娱乐",
    "影视": "娱乐",
    "电影": "娱乐",
    "音乐": "娱乐",
    "entertainment": "娱乐",
    "movie": "娱乐",
    "film": "娱乐",
    "社会新闻": "社会",
    "时政": "社会",
    "国内": "社会",
    "国际": "社会",
    "政务": "社会",
    "society": "社会",
    "social": "社会",
    "news": "社会",
    "学校": "教育",
    "考试": "教育",
    "升学": "教育",
    "留学": "教育",
    "education": "教育",
    "edu": "教育",
    "军情": "军事",
    "国防": "军事",
    "武器": "军事",
    "military": "军事",
    "army": "军事",
    "defense": "军事",
    "车": "汽车",
    "车市": "汽车",
    "新车": "汽车",
    "用车": "汽车",
    "auto": "汽车",
    "car": "汽车",
    "cars": "汽车",
    "automobile": "汽车",
    "vehicle": "汽车",
}

MODEL_DISPLAY_NAMES: dict[str, str] = {
    "best": "最佳模型",
    "nb": "朴素贝叶斯",
    "lr": "逻辑回归",
    "svm": "线性 SVM",
    "textcnn": "TextCNN",
}

DEFAULT_MODEL_VERSION = "news-text-v1"
